"""Fix-outcome ledger: exact worked/partial/failed counts computed directly from
backend/data/seed_incidents.json (plus, later, any live feedback).

Hindsight is never used for counts -- recall is similarity search over natural-language
memories, not a reliable source of exact aggregate numbers (chunking, dedup and
relevance-ranking mean recall can under- or over-return matches). The ranking formula in
scoring.py needs exact counts, so this module is the single source of truth for them and
writes backend/data/ledger.json, which is gitignored (regenerated by POST /seed, not
committed -- see docs/CONTRACT_ISSUES.md for the .gitignore entry, which is user-owned
per docs/AGENTS.md so this project doesn't add it directly).
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
LEDGER_PATH = DATA_DIR / "ledger.json"


def compute_ledger(incidents: list[dict[str, Any]]) -> dict[str, Any]:
    rows: dict[tuple[str, str, str], dict[str, Any]] = {}
    totals = {"worked": 0, "partial": 0, "failed": 0}

    for incident in incidents:
        service = incident["service"]
        error_signature = incident["error_signature"]
        incident_id = incident["incident_id"]
        for fix in incident["fix_attempts"]:
            key = (service, error_signature, fix["fix_type"])
            row = rows.setdefault(
                key,
                {
                    "service": service,
                    "error_signature": error_signature,
                    "fix_type": fix["fix_type"],
                    "worked": 0,
                    "partial": 0,
                    "failed": 0,
                    "incident_ids": [],
                },
            )
            row[fix["outcome"]] += 1
            row["incident_ids"].append(incident_id)
            totals[fix["outcome"]] += 1

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "counts": sorted(rows.values(), key=lambda r: (r["service"], r["error_signature"], r["fix_type"])),
        "totals": {
            "incidents": len(incidents),
            "fix_attempts": sum(len(i["fix_attempts"]) for i in incidents),
            **totals,
        },
    }


def write_ledger(incidents: list[dict[str, Any]]) -> dict[str, Any]:
    ledger = compute_ledger(incidents)
    LEDGER_PATH.write_text(json.dumps(ledger, indent=2), encoding="utf-8")
    return ledger


def read_ledger() -> dict[str, Any] | None:
    if not LEDGER_PATH.exists():
        return None
    return json.loads(LEDGER_PATH.read_text(encoding="utf-8"))


def counts_for_signature(
    error_signature: str,
    ledger_data: dict[str, Any],
    live_feedback: list[dict[str, Any]] | None = None,
) -> dict[str, dict[str, Any]]:
    """fix_type -> {worked, partial, failed, incident_ids} for every fix attempted on
    incidents of this error_signature, merging the seed ledger with live feedback
    entries (POST /feedback) of the same signature. Used by scoring.rank_fixes() for its
    worked/partial/failed/attempts inputs -- never Hindsight."""
    result: dict[str, dict[str, Any]] = {}

    for row in ledger_data.get("counts", []):
        if row["error_signature"] != error_signature:
            continue
        agg = result.setdefault(row["fix_type"], {"worked": 0, "partial": 0, "failed": 0, "incident_ids": []})
        agg["worked"] += row["worked"]
        agg["partial"] += row["partial"]
        agg["failed"] += row["failed"]
        agg["incident_ids"] += row["incident_ids"]

    for entry in live_feedback or []:
        if entry.get("error_signature") != error_signature:
            continue
        agg = result.setdefault(entry["fix_type"], {"worked": 0, "partial": 0, "failed": 0, "incident_ids": []})
        agg[entry["outcome"]] += 1
        agg["incident_ids"].append(entry["incident_id"])

    return result
